sudo: false

language: python

python:
  - '2.7'
  - '3.6'

env:
  - DJANGO='django>=1.11.0,<2.0.0'
  - DJANGO='django>=1.10.0,<1.11.0'
  - DJANGO='django>=1.9.0,<1.10.0'
  - DJANGO='django>=1.8.0,<1.9.0'

install:
  - travis_retry pip install $DJANGO
  
script:
  - ./manage.py test
